export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_EMAIL_OTP_REQUEST = 'USER_EMAIL_OTP_REQUEST';
export const USER_EMAIL_OTP_SUCCESS = 'USER_EMAIL_OTP_SUCCESS';
export const USER_EMAIL_OTP_FAIL = 'USER_EMAIL_OTP_FAIL';

export const USER_EMAIL_PASSWORD_CHANGE_REQUEST = 'USER_EMAIL_PASSWORD_CHANGE_REQUEST'; 
export const USER_EMAIL_PASSWORD_CHANGE_SUCCESS = 'USER_EMAIL_PASSWORD_CHANGE_SUCCESS';
export const USER_EMAIL_PASSWORD_CHANGE_FAIL = 'USER_EMAIL_PASSWORD_CHANGE_FAIL';

export const  LOGIN_WITH_GOOGLE_FACEBOOK_REQUEST = 'LOGIN_WITH_GOOGLE_FACEBOOK_REQUEST';
export const  LOGIN_WITH_GOOGLE_FACEBOOK_SUCCESS = 'LOGIN_WITH_GOOGLE_FACEBOOK_SUCCESS';
export const  LOGIN_WITH_GOOGLE_FACEBOOK_FAIL = 'LOGIN_WITH_GOOGLE_FACEBOOK_FAIL';
export const  LOGOUT_WITH_GOOGLE_FACEBOOK = 'LOGOUT_WITH_GOOGLE_FACEBOOK';