export const ActionTypes = {
  USER_LOGIN: "USER_LOGIN",
  USER_REGISTER: "USER_REGISTER",
  USER_UPDATE: "USER_UPDATE",

  EDIT_TEMPLATE: "EDIt_TEMPLATE",
  GET_ALL_TEMPLATES: "GET_TEMPLATES",
  GET_TEMPLATE: "GET_TEMPLATE",
  UPDATE_TEMPLATE: "UPDATE_TEMPLATE",

  EVENT_DETAILS: "EVENT_DETAILS",

  SET_ACTIVE_TITLE: "SET_ACTIVE_TITLE",
};
