export const ActionTypes = {
  USER_LOGIN: "USER_LOGIN",
  USER_REGISTER: "USER_REGISTER",
  USER_UPDATE: "USER_UPDATE",
  USER_AUTH: "USER_AUTH",
  USER_LOGOUT: "USER_LOGOUT",

  EDIT_TEMPLATE: "EDIt_TEMPLATE",
  GET_ALL_TEMPLATES: "GET_TEMPLATES",
  GET_TEMPLATE: "GET_TEMPLATE",
  UPDATE_TEMPLATE: "UPDATE_TEMPLATE",
  SET_CREATED_EVENT_DETAILS: "SET_CREATED_EVENT_DETAILS",
  RESET_CREATED_EVENT_DETAILS: "RESET_CREATED_EVENT_DETAILS",
  SET_CREATED_LIST_ID: "SET_CREATED_LIST_ID",

  EVENT_DETAILS: "EVENT_DETAILS",

  SET_ACTIVE_TITLE: "SET_ACTIVE_TITLE",

  SET_ACTIVE_TEMPLATE: "SET_ACTIVE_TEMPLATE",
  RESET_ACTIVE_TEMPLATE: "RESET_ACTIVE_TEMPLATE",

  SET_EVENT_DETAILS: "SET_EVENT_DETAILS",
  RESET_EVENT_DETAILS: "RESET_EVENT_DETAILS",

  SET_EVENT_TEMPLATE_JSON: "SET_EVENT_TEMPLATE_JSON",
  RESET_EVENT_TEMPLATE_JSON: "RESET_EVENT_TEMPLATE_JSON",

  OPEN_SNACKBAR: "OPEN_SNACKBAR",
  CLOSE_SNACKBAR: "CLOSE_SNACKBAR",
};

export const Constants = {
  IMG_URL: "http://localhost:8085/api/v1/user",
  URL: "/api/v1/user",
  IMG_PATH: "/images/getImage?path=",
};
