export const TEMPLATE_LIST_REQUEST = 'TEMPLATE_LIST_REQUEST'; 
export const TEMPLATE_LIST_SUCCESS = 'TEMPLATE_LIST_SUCCESS'; 
export const TEMPLATE_LIST_FAIL =  'TEMPLATE_LIST_FAIL';

export const TEMPLATE_DETAILS_REQUEST = 'TEMPLATE_DETAILS_REQUEST';
export const TEMPLATE_DETAILS_SUCCESS = 'TEMPLATE_DETAILS_SUCCESS';
export const TEMPLATE_DETAILS_FAIL = 'TEMPLATE_DETAILS_FAIL';

export const TEMPLATE_EDIT_REQUEST = 'TEMPLATE_EDIT_REQUEST';
export const TEMPLATE_EDIT_SUCCESS = 'TEMPLATE_EDIT_SUCESS';
export const TEMPLATE_EDIT_FAIL =  'TEMPLATE_EDIT_FAIL';

export const ADD_EVENT_DETAILS_REQUEST = 'ADD_EVENT_DETAILS_REQUEST';  
export const ADD_EVENT_DETAILS_SUCCESS =  'ADD_EVENT_DETAILS_SUCCESS';
export const ADD_EVENT_DETAILS_FAIL =   'ADD_EVENT_DETAILS_FAIL';

export const ADD_SINGLE_AND_MULTIPAL_GUEST_REQUEST = 'ADD_SINGLE_AND_MULTIPAL_GUEST_REQUEST';
export const ADD_SINGLE_AND_MULTIPAL_GUEST_SUCCESS = 'ADD_SINGLE_AND_MULTIPAL_GUEST_SUCCESS'; 
export const ADD_SINGLE_AND_MULTIPAL_GUEST_FAIL = 'ADD_SINGLE_AND_MULTIPAL_GUEST_FAIL';

export const GET_EDIT_SINGLE_GUESTDETAILS_REQUEST = 'GET_EDIT_SINGLE_GUESTDETAILS_REQUEST';
export const GET_EDIT_SINGLE_GUESTDETAILS_SUCCESS = 'GET_EDIT_SINGLE_GUESTDETAILS_SUCCESS';
export const GET_EDIT_SINGLE_GUESTDETAILS_FAIL = 'GET_EDIT_SINGLE_GUESTDETAILS_FAIL';

export const GET_SINGLE_EDIT_TEMPLATE_REQUEST = " GET_SINGLE_EDIT_TEMPLATE_REQUEST"; 
export const GET_SINGLE_EDIT_TEMPLATE_SUCCESS = " GET_SINGLE_EDIT_TEMPLATE_SUCCESS"; 
export const GET_SINGLE_EDIT_TEMPLATE_FAIL = " GET_SINGLE_EDIT_TEMPLATE_FAIL";