export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

export const ADMIN_EMAIL_OTP_REQUEST = "ADMIN_EMAIL_OTP_REQUEST";
export const ADMIN_EMAIL_OTP_SUCCESS = "ADMIN_EMAIL_OTP_SUCCESS";
export const ADMIN_EMAIL_OTP_FAIL = "ADMIN_EMAIL_OTP_FAIL";

export const ADMIN_EMAIL_PASSWORD_CHANGE_REQUEST =
  "ADMIN_EMAIL_PASSWORD_CHANGE_REQUEST";
export const ADMIN_EMAIL_PASSWORD_CHANGE_SUCCESS =
  "ADMIN_EMAIL_PASSWORD_CHANGE_SUCCESS";
export const ADMIN_EMAIL_PASSWORD_CHANGE_FAIL =
  "ADMIN_EMAIL_PASSWORD_CHANGE_FAIL";

export const ADMIN_USER_LIST_REQUEST = "ADMIN_USER_LIST_REQUEST";
export const ADMIN_USER_LIST_SUCCESS = "ADMIN_USER_LIST_SUCCESS";
export const ADMIN_USER_LIST_FAIL = "ADMIN_USER_LIST_FAIL";

export const SUB_ADMIN_LIST_REQUEST = "SUB_ADMIN_LIST_REQUEST";
export const SUB_ADMIN_LIST_SUCCESS = "SUB_ADMIN_LIST_SUCCESS";
export const SUB_ADMIN_LIST_FAIL = "SUB_ADMIN_LIST_FAIL";

export const ADMIN_USER_DELETE_REQUEST = "ADMIN_USER_DELETE_REQUEST";
export const ADMIN_USER_DELETE_SUCCESS = "ADMIN_USER_DELETE_SUCCESS";
export const ADMIN_USER_DELETE_FAIL = "ADMIN_USER_DELETE_FAIL";

export const ADMIN_TEMPLATE_CREATE_REQUEST = "ADMIN_TEMPLATE_CREATE_REQUEST";
export const ADMIN_TEMPLATE_CREATE_SUCCESS = "ADMIN_TEMPLATE_CREATE_FAIL";
export const ADMIN_TEMPLATE_CREATE_FAIL = "ADMIN_TEMPLATE_CREATE_FAIL";
export const ADMIN_TEMPLATE_CREATE_RESET = "ADMIN_TEMPLATE_CREATE_RESET";

export const ADMIN_ALL_TEMPLATE_LIST_REQUEST =
  "ADMIN_ALL_TEMPLATE_LIST_REQUEST";
export const ADMIN_ALL_TEMPLATE_LIST_SUCCESS =
  "ADMIN_ALL_TEMPLATE_LIST_SUCCESS";
export const ADMIN_ALL_TEMPLATE_LIST_FAIL = "ADMIN_ALL_TEMPLATE_LIST_FAIL";

export const ADMIN_REGISTER_REQUEST = "SUB_ADMIN_REGISTER_REQUEST";
export const ADMIN_REGISTER_SUCCESS = "SUB_ADMIN_REGISTER_SUCCESS";
export const ADMIN_REGISTER_FAIL = "SUB_ADMIN_REGISTER_FAIL";

export const ADMIN_TEMPLATE_DETAILS_REQUEST = "ADMIN_TEMPLATE_DETAILS_REQUEST";
export const ADMIN_TEMPLATE_DETAILS_SUCCESS = "ADMIN_TEMPLATE_DETAILS_SUCCESS";
export const ADMIN_TEMPLATE_DETAILS_FAIL = "ADMIN_TEMPLATE_DETAILS_FAIL";

export const ADMIN_TEMPLATE_EDIT_LIST_REQUEST =
  "ADMIN_TEMPLATE_EDIT_LIST_REQUEST";
export const ADMIN_TEMPLATE_EDIT_LIST_SUCCESS =
  "ADMIN_TEMPLATE_EDIT_LIST_SUCCESS";
export const ADMIN_TEMPLATE_EDIT_LIST_FAIL = "ADMIN_TEMPLATE_EDIT_LIST_FAIL";

export const ADMIN_TEMPLATE_DELETE_REQUEST = "ADMIN_TEMPLATE_DELETE_REQUEST";
export const ADMIN_TEMPLATE_DELETE_SUCCESS = "ADMIN_TEMPLATE_DELETE_SUCCESS";
export const ADMIN_TEMPLATE_DELETE_FAIL = "ADMIN_TEMPLATE_DELETE_FAIL";

export const ADMIN_TEMPLATE_UPDATE_LIST_REQUEST =
  "ADMIN_TEMPLATE_UPDATE_LIST_REQUEST";
export const ADMIN_TEMPLATE_UPDATE_LIST_SUCCESS =
  "ADMIN_TEMPLATE_UPDATE_LIST_SUCCESS";
export const ADMIN_TEMPLATE_UPDATE_LIST_FAIL =
  "ADMIN_TEMPLATE_UPDATE_LIST_FAIL";
export const ADMIN_TEMPLATE_UPDATE_LIST_RESET =
  "ADMIN_TEMPLATE_UPDATE_LIST_RESET";

export const ADMIN_SUBSCRIPTIONS_LIST_REQUEST =
  "ADMIN_SUBSCRIPTIONS_LIST_REQUEST";
export const ADMIN_SUBSCRIPTIONS_LIST_SUCCESS =
  "ADMIN_SUBSCRIPTIONS_LIST_SUCCESS";
export const ADMIN_SUBSCRIPTIONS_LIST_FAIL = "ADMIN_SUBSCRIPTIONS_LIST_FAIL";
